/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JHathor */

#ifndef _Included_JHathor
#define _Included_JHathor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JHathor
 * Method:    xs
 * Signature: (IDDD)D
 */
JNIEXPORT jdouble JNICALL Java_JHathor_xs
  (JNIEnv *, jobject, jint, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
